apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
  name: llama-3-1-8b-instruct-1xgpu
spec:
  predictor:
    tolerations:
      - key: odh-notebook
        operator: Exists
        effect: NoSchedule
    minReplicas: 1
    model:
      modelFormat:
        name: nvidia-nim-llama-3.1-8b-instruct
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: nvidia-nim-llama-3.1-8b-instruct-1.1.2
      storageUri: pvc://nvidia-nim-pvc/

    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
