apiVersion: batch/v1
kind: Job
metadata:
  name: nim-download-single-job
spec:
  template:
    metadata:
      name: nim-download-single-pod
    spec:
      tolerations:
        - key: odh-notebook
          operator: Exists
          effect: NoSchedule
      containers:
      - name: nim-download-single
        # Update the image name to the NIM that will be deployed in production
        image: nvcr.io/nim/meta/llama-3.1-8b-instruct:1.1.2
        args: ["download-to-cache"]
        env:
        - name: NIM_CACHE_PATH
          value: /mnt/models/cache
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nvidia-nim-secrets
              key: NGC_API_KEY    
        volumeMounts:
        - name: model-cache
          mountPath: /mnt/models/

        # Update the number of GPUs desired for production deployment
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
      imagePullSecrets:
      - name: ngc-secret
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: nvidia-nim-pvc
      
      # Update the type of GPU desired for production deployment
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      restartPolicy: Never
